export const TRIPS = [
  {
    src: "https://themes-themegoods.b-cdn.net/grandtour/demo/wp-content/uploads/2016/12/pexels-photo-211051-700x466.jpeg",
    originalPrice: 5000,
    salesPrice: 5000,
    specials: ["City Tours", "Urban"],
    reviewQuantity: 4,
    duration: 5,
    href: "#",
    title: "Frech Autumn",
  },
  {
    src: "https://themes-themegoods.b-cdn.net/grandtour/demo/wp-content/uploads/2016/12/pexels-photo-197657-700x466.jpeg",
    originalPrice: 6000,
    salesPrice: 6000,
    specials: ["Shopping Mountain", "Snow & Ice"],
    reviewQuantity: 4,
    duration: 6,
    href: "#",
    title: "Grand Switzerland",
  },
  {
    src: "https://themes-themegoods.b-cdn.net/grandtour/demo/wp-content/uploads/2016/12/pexels-photo-96420-700x466.jpeg",
    originalPrice: 3000,
    salesPrice: 2500,
    specials: ["City Tours", "Iconic"],
    reviewQuantity: 4,
    duration: 5,
    href: "#",
    title: "Discover Japan",
  },
];
